package com.ram.researchdesk

/**
 * Port of flutter_app/lib/data/curriculum.dart — BDS curriculum (Years 1–4)
 * with subject metadata filled in: blurbs, domains, default literature
 * queries, synonyms, departmental equipment and ethics watch-lists.
 */

data class ClusterSeed(
    val id: String,
    val name: String,
    val keywords: List<String> = emptyList(),
    val exposures: List<String> = emptyList(),
    val outcomes: List<String> = emptyList(),
    val methods: List<String> = emptyList(),
)

data class Year(
    val id: String,
    val numeral: String,
    val name: String,
    val kicker: String = "",
    val subjectCount: Int = 0,
)

data class Subject(
    val id: String,
    val name: String,
    val year: String,
    val blurb: String = "",
    val domains: List<String> = emptyList(),
    val defaultQuery: String = "",
    val synonyms: List<String> = emptyList(),
    val clusters: List<ClusterSeed> = emptyList(),
    val equipment: List<String> = emptyList(),
    val ethicsWatch: List<String> = emptyList(),
    val topics: List<String> = emptyList(),
)

val YEARS: List<Year> = listOf(
    Year(
        id = "first",
        numeral = "I",
        name = "First BDS",
        kicker = "Foundations of the human body — normal structure and function",
    ),
    Year(
        id = "second",
        numeral = "II",
        name = "Second BDS",
        kicker = "Disease mechanisms, dental materials and drugs entering the clinic",
    ),
    Year(
        id = "third",
        numeral = "III",
        name = "Third BDS",
        kicker = "Clinical sciences — diagnosis, prevention and treatment planning",
    ),
    Year(
        id = "final",
        numeral = "IV",
        name = "Final BDS",
        kicker = "Specialty practice, community health and interdisciplinary work",
    ),
)

val SUBJECTS: List<Subject> = listOf(

    // ---------------- First BDS ----------------

    Subject(
        id = "anatomy",
        name = "General Anatomy",
        year = "first",
        blurb = "Gross anatomy with a head–neck emphasis for dental practice, plus histology and embryology.",
        domains = listOf(
            "Head & Neck Anatomy", "Cranial Nerves", "Orbit & Paranasal Sinuses",
            "TMJ & Masticatory Muscles", "Infratemporal & Pterygopalatine Fossae",
            "Oral Cavity, Tongue & Palate", "Pharynx & Larynx",
            "Thorax & Heart", "Abdomen & Pelvis", "Neuroanatomy",
            "Histology of Oral Tissues", "Embryology of Face & Teeth",
            "Medical Genetics", "Osteology & Forensic Identification",
        ),
        defaultQuery = "anatomical variation head neck morphometry cadaveric study dental",
        synonyms = listOf(
            "gross anatomy", "human anatomy", "morphometry",
            "anatomical variation", "foramen", "ossification",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-anat-morphometry",
                name = "Craniofacial morphometry",
                keywords = listOf("morphometry", "foramen", "mandible", "measurements"),
                exposures = listOf("dry skull side", "sex", "age group"),
                outcomes = listOf("linear distances", "foramen diameters", "angles"),
                methods = listOf("caliper measurement", "osteology recording sheet", "ImageJ on photographs"),
            ),
            ClusterSeed(
                id = "seed-anat-variations",
                name = "Anatomical variations",
                keywords = listOf("variation", "accessory", "anomaly", "incidence"),
                exposures = listOf("population side", "cadaver cohort"),
                outcomes = listOf("incidence percentages"),
                methods = listOf("dissection records review", "photographic documentation"),
            ),
        ),
        equipment = listOf(
            "sliding caliper", "digital vernier caliper", "measuring tape",
            "hand lens", "microscope slides", "articulated skull set",
        ),
        ethicsWatch = listOf(
            "cadaveric material handling per university norms",
            "written consent for clinical photographs",
            "no dissection beyond curriculum without IEC approval",
        ),
        topics = listOf(
            "Anatomical terminology", "Skin superficial and deep fascia", "Cardiovascular system and portal system",
            "Lymphatic system and regional lymph nodes", "Osteology ossification bone growth", "Myology muscle types innervation",
            "Syndesmology joint classification", "Scalp", "Face", "Temple", "Lacrimal apparatus",
            "Neck deep fascia triangles", "Cranial cavity meninges brain ventricles dural sinuses",
            "Cranial nerves III to XII", "Orbital cavity", "Parotid gland",
            "TMJ and muscles of mastication", "Infratemporal fossa", "Pterygopalatine fossa",
            "Submandibular region", "Nasal cavity and paranasal sinuses", "Palate",
            "Oral cavity and tongue", "Pharynx and larynx", "Foetal and adult skull", "Cervical vertebrae",
            "Thoracic wall and heart", "Coronary arteries", "Lungs and pleura", "Diaphragm",
            "Peritoneal cavity", "Abdominal and pelvic organs",
            "IM injection sites", "IV injection and venesection", "Arterial pulsation points",
            "Oogenesis and spermatogenesis", "Fertilisation and placenta",
            "Pharyngeal arches pouches and clefts", "Development of face tongue palate", "Tooth development",
            "Histology epithelium connective tissue muscle nervous tissue", "Medical genetics mitosis meiosis chromosomes Mendelism",
        ),
    ),

    Subject(
        id = "physiology",
        name = "Physiology",
        year = "first",
        blurb = "Systemic human physiology with practical emphasis on cardiorespiratory, hematological and nerve–muscle experiments.",
        domains = listOf(
            "Blood & Hematology", "Cardiovascular System", "Respiratory System",
            "Gastrointestinal & Salivary Glands", "Renal Physiology",
            "Endocrinology", "Nerve-Muscle Physiology", "CNS & Special Senses",
            "Reproductive Physiology", "Body Temperature & Skin",
        ),
        defaultQuery = "dental students blood pressure heart rate stress physiological measurement",
        synonyms = listOf(
            "human physiology", "cardiovascular", "spirometry",
            "reaction time", "vital signs",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-phys-cv",
                name = "Cardiovascular responses",
                keywords = listOf("blood pressure", "heart rate", "response", "exercise"),
                exposures = listOf("posture", "caffeine", "exam stress", "audio stimulation"),
                outcomes = listOf("SBP/DBP", "pulse rate", "SpO2"),
                methods = listOf("sphygmomanometer", "pulse oximeter", "standardized protocol sheet"),
            ),
            ClusterSeed(
                id = "seed-phys-resp",
                name = "Respiratory measures",
                keywords = listOf("peak flow", "spirometry", "respiratory"),
                exposures = listOf("anthropometry", "physical activity level"),
                outcomes = listOf("PEFR", "breath-holding time"),
                methods = listOf("peak flow meter", "triplicate recording"),
            ),
        ),
        equipment = listOf(
            "sphygmomanometer", "stethoscope", "pulse oximeter",
            "peak flow meter", "hand-grip dynamometer", "reaction-time board/app",
        ),
        ethicsWatch = listOf(
            "volunteer informed consent",
            "no invasive sampling in UG projects",
            "stop rules for dizziness or exertion discomfort",
        ),
        topics = listOf(
            "Homeostasis and feedback mechanisms", "Cell membrane transport", "Membrane potentials",
            "Blood composition and functions", "Plasma proteins", "Erythropoiesis and anemia",
            "Hemoglobin", "Blood indices MCV MCH MCHC", "Leucocytes and immunity",
            "Thrombocytes and hemostasis", "Blood groups ABO Rh", "Body fluid compartments",
            "Skeletal muscle contraction", "Neuromuscular transmission", "Cardiac and smooth muscle properties",
            "Salivary glands and saliva", "Stomach and gastric juice", "Liver and bile",
            "Mastication and deglutition", "Kidney structure and nephron", "GFR",
            "Tubular reabsorption", "Acid-base regulation", "Body temperature regulation",
            "Pituitary hormones", "Thyroid function tests", "Adrenal cortex and medulla",
            "Menstrual cycle", "Spermatogenesis and contraception",
            "Cardiac cycle", "ECG", "Blood pressure regulation", "Coronary circulation",
            "Spirometry and lung volumes", "Gas exchange", "O2 and CO2 transport", "Hypoxia and cyanosis",
            "Spinal cord organization", "Synapse and reflexes", "Cerebellum and thalamus", "CSF",
            "Autonomic nervous system", "Vision and hearing", "Taste and smell",
        ),
    ),

    Subject(
        id = "biochemistry",
        name = "Biochemistry",
        year = "first",
        blurb = "Biomolecules, enzymes and metabolism with chairside-relevant applications such as salivary pH and buffering.",
        domains = listOf(
            "Carbohydrates & Energy Metabolism", "Lipids & Lipoproteins",
            "Proteins & Amino Acids", "Enzymes & Metabolic Regulation",
            "Vitamins & Deficiency", "Minerals & Calcium Metabolism",
            "Salivary Biochemistry (pH, Buffering, Amylase)",
            "Molecular Biology & Genetics", "Clinical Biochemistry (LFT, KFT, Glucose)",
            "Hemoglobin & Porphyria", "Immunoglobulins",
        ),
        defaultQuery = "saliva pH buffering capacity dental caries biochemical assay",
        synonyms = listOf(
            "salivary biochemistry", "pH", "buffering capacity",
            "biomarkers", "enzymes",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-bioch-ph",
                name = "Salivary pH & buffering",
                keywords = listOf("saliva", "pH", "buffering", "flow rate"),
                exposures = listOf("time of day", "sugary drink challenge", "fasting status", "oral hygiene"),
                outcomes = listOf("unstimulated salivary pH", "buffering score"),
                methods = listOf("pH strip or meter", "stimulated saliva collection"),
            ),
            ClusterSeed(
                id = "seed-bioch-enzymes",
                name = "Enzyme markers",
                keywords = listOf("enzyme", "amylase", "activity", "assay"),
                exposures = listOf("stress", "diet pattern", "smoking status"),
                outcomes = listOf("amylase activity", "colorimetric readings"),
                methods = listOf("colorimetric kit assay", "colorimeter/spectrophotometer"),
            ),
        ),
        equipment = listOf(
            "pH strips", "portable pH meter", "colorimeter",
            "centrifuge (shared facility)", "graduated pipettes", "water bath",
        ),
        ethicsWatch = listOf(
            "saliva collection informed consent",
            "no blood collection without IEC approval",
            "biosafety for sample handling and disposal",
        ),
        topics = listOf(
            "Carbohydrates mono disaccharides polysaccharides", "Lipids fatty acids cholesterol bile salts",
            "Proteins amino acids peptides buffers", "Nucleic acids DNA RNA ATP",
            "Energy needs and BMR", "Dietary fiber", "Essential fatty acids", "Protein quality and PCM",
            "Balanced diet", "Enzymatic digestion and absorption",
            "Vitamins classification and deficiencies", "Vitamin D and calcium metabolism",
            "Minerals calcium phosphate iron iodine fluoride",
            "Glycolysis", "Citric acid cycle", "Beta-oxidation", "Electron transport chain",
            "Glycogenesis and glycogenolysis", "Fatty acid synthesis", "Gluconeogenesis",
            "Pentose phosphate pathway", "Cholesterol synthesis", "Ammonia metabolism and urea cycle",
            "DNA replication", "Transcription and translation", "Genetic code and mutation",
            "Enzyme classification and inhibitors", "Isoenzymes", "Second messengers cAMP Ca2+",
            "Insulin and glucagon action", "Collagen elastin glycosaminoglycans",
            "Hemoglobin and heme metabolism", "Plasma proteins and immunoglobulins",
            "Lipoproteins", "Blood glucose regulation and diabetes",
            "Liver function tests", "Kidney function tests", "Acid-base and electrolyte imbalance",
            "Saliva analysis amylase", "Glucose tolerance test",
        ),
    ),

    Subject(
        id = "dental-anatomy",
        name = "Dental Anatomy",
        year = "first",
        blurb = "Morphology, occlusion and identification of teeth; tooth carving and crown dimension recording.",
        domains = listOf(
            "Tooth Morphology (Permanent & Deciduous)", "Odontometry & Crown Dimensions",
            "Occlusion & jaw relations", "Tooth Identification & Notation Systems",
            "Oral Embryology (Face, Jaws, Palate, Teeth Development)",
            "Oral Histology (Enamel, Dentine, Cementum, PDL, Bone)",
            "Salivary Gland Histology", "TMJ Histology",
            "Oral Physiology (Saliva, Mastication, Deglutition, Taste, Speech)",
            "Calcium-Phosphorus-Fluoride Metabolism", "Calculus Formation",
        ),
        defaultQuery = "tooth morphology crown dimensions odontometry caries prevalence",
        synonyms = listOf(
            "tooth morphology", "odontometry", "crown dimensions",
            "mesiodistal", "buccolingual",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-dent-odontometry",
                name = "Odontometry",
                keywords = listOf("mesiodistal", "buccolingual", "dimensions", "odontometry"),
                exposures = listOf("tooth type", "sex", "arch side"),
                outcomes = listOf("crown widths", "coronal heights"),
                methods = listOf("digital caliper", "ImageJ photogrammetry"),
            ),
            ClusterSeed(
                id = "seed-dent-caries",
                name = "Early caries indicators",
                keywords = listOf("caries", "prevalence", "DMFT", "children"),
                exposures = listOf("diet", "fluoride exposure", "oral hygiene habits"),
                outcomes = listOf("DMFT/dmft index", "visible lesions"),
                methods = listOf("screening under torchlight", "WHO oral assessment form"),
            ),
        ),
        equipment = listOf(
            "digital vernier caliper", "extracted-tooth collection (departmental)",
            "ImageJ", "wax blocks and carving instruments", "millimeter graph sheets",
        ),
        ethicsWatch = listOf(
            "extracted-tooth storage and disposal per biomedical waste rules",
            "de-identification of casts and photographs",
        ),
        topics = listOf(
            "Human dentition overview", "Notation systems Palmer and FDI", "Tooth surfaces line and point angles",
            "Contact areas and embrasures", "Permanent teeth morphology",
            "Endodontic anatomy of teeth", "Tooth chronology", "Tooth anomalies",
            "Deciduous teeth morphology", "Occlusion centric relation and occlusion",
            "Protrusive and lateral occlusion", "Malocclusion classification",
            "Development of face and jaws", "Development of lip and palate",
            "Development of teeth stages of crown and root", "Eruption of deciduous and permanent teeth",
            "Shedding of teeth", "Enamel structure and properties", "Dentine structure and tubules",
            "Cementum", "Pulp anatomy and age changes", "Periodontal ligament", "Alveolar bone",
            "Oral mucosa and keratinization", "Gingiva structure", "Lingual papillae",
            "Salivary gland histology", "TMJ histology", "Maxillary sinus",
            "Saliva composition and secretion", "Role of saliva in caries",
            "Mastication force measurement", "Deglutition physiology",
            "Calcium phosphorus fluoride metabolism", "Calculus formation theories",
            "Taste physiology", "Speech physiology",
        ),
    ),

    // ---------------- Second BDS ----------------

    Subject(
        id = "dental-materials",
        name = "Dental Materials",
        year = "second",
        blurb = "Physical, chemical and mechanical properties of restorative materials with simple laboratory testing options.",
        domains = listOf(
            "Gypsum Products", "Impression Materials (Hydrocolloid, Elastomers)",
            "Resin Composites & Bonding", "Glass Ionomer Cements",
            "Dental Amalgam", "Metals, Alloys & Casting",
            "Dental Ceramics & Porcelain", "Acrylic Resins & Denture Base",
            "Waxes & Investments", "Soldering & Welding",
            "Orthodontic Wires (NiTi, SS, Beta-Ti)",
            "Dental Implants (Biomaterials, Osseointegration)",
            "Biocompatibility & Testing", "Physical Properties & Adhesion",
        ),
        defaultQuery = "glass ionomer resin composite surface roughness flexural strength in vitro",
        synonyms = listOf(
            "biomaterials", "glass ionomer", "composite resin",
            "polymerization", "hardness",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-mat-mechanical",
                name = "Mechanical properties",
                keywords = listOf("flexural", "compressive", "strength", "hardness"),
                exposures = listOf("material brand", "filler load", "curing time"),
                outcomes = listOf("MPa values", "hardness numbers"),
                methods = listOf("UTM three-point bend test", "microhardness testing"),
            ),
            ClusterSeed(
                id = "seed-mat-surface",
                name = "Surface behavior",
                keywords = listOf("surface roughness", "wear", "polish", "staining"),
                exposures = listOf("polishing protocol", "beverage immersion", "brushing cycles"),
                outcomes = listOf("Ra roughness values", "color change ΔE"),
                methods = listOf("profilometer/ImageJ", "color measurement app", "immersion cycle protocol"),
            ),
        ),
        equipment = listOf(
            "universal testing machine (central facility)", "pH meter", "ImageJ",
            "articulator", "stone casts", "polishing kits",
        ),
        ethicsWatch = listOf(
            "material safety data sheet handling",
            "sharps disposal protocol",
            "no intraoral testing of new materials without IEC",
        ),
        topics = listOf(
            "Performance standards for dental materials", "Structure of matter and adhesion",
            "Physical properties mechanical optical thermal", "Biocompatibility and biocompatibility testing",
            "Gypsum products plaster stone die stone", "Setting chemistry of gypsum",
            "Impression materials hydrocolloid elastomers", "Silicones and polyether",
            "Synthetic resins and polymerization", "Acrylic denture base resins",
            "Restorative composites composition and curing", "Polymerization shrinkage",
            "Bonding and acid-etch technique", "Dentin bonding agents",
            "Pit and fissure sealants", "Resin inlays",
            "Dental amalgam setting reaction and properties", "Mercury hygiene",
            "Direct filling gold", "Dental casting alloys noble and base metal",
            "Titanium alloys", "CAD-CAM alternatives",
            "Dental waxes", "Casting investments gypsum and phosphate bonded",
            "Soldering and brazing", "Laser welding",
            "Orthodontic wires stainless steel NiTi beta-titanium",
            "Dental cements glass ionomer zinc phosphate polycarboxylate",
            "Liners bases and varnish", "Calcium hydroxide",
            "Dental ceramics and porcelain", "Metal-ceramic restorations",
            "Abrasion and polishing agents", "Die and counter-die materials",
            "Dental implants biomaterials and biomechanics", "Mechanics of cutting and bur efficiency",
        ),
    ),

    Subject(
        id = "pathology",
        name = "General Pathology",
        year = "second",
        blurb = "Disease mechanisms, inflammation and neoplasia with hematology practicals and clinicopathologic correlation.",
        domains = listOf(
            "Cell Injury & Necrosis", "Inflammation & Healing",
            "Hematology (Anemia, Leukemia, Bleeding Disorders)",
            "Neoplasia & Carcinogenesis", "Immunopathology & Hypersensitivity",
            "Infections (TB, Syphilis, AIDS)", "Cardiovascular Pathology",
            "Nutritional Disorders", "Oral Cavity Diseases",
            "Salivary Gland Pathology", "Bone Diseases",
            "Cysts & Tumors of Jaws", "Mucocutaneous Lesions",
        ),
        defaultQuery = "anemia prevalence hemoglobin estimation dental outpatient patients",
        synonyms = listOf("hemoglobin", "anemia", "inflammation", "ESR", "blood film"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-path-anemia",
                name = "Anemia burden",
                keywords = listOf("anemia", "hemoglobin", "prevalence", "deficiency"),
                exposures = listOf("sex", "diet pattern", "age group"),
                outcomes = listOf("Hb g/dL", "clinical pallor signs"),
                methods = listOf("hemoglobinometer", "structured proforma"),
            ),
            ClusterSeed(
                id = "seed-path-inflammation",
                name = "Inflammatory markers",
                keywords = listOf("ESR", "CRP", "inflammation", "marker"),
                exposures = listOf("periodontal status", "systemic condition"),
                outcomes = listOf("ESR mm/hr", "CRP tiers"),
                methods = listOf("record-based review", "lab report extraction"),
            ),
        ),
        equipment = listOf(
            "hemoglobinometer (capillary)", "microscope", "staining reagents",
            "centrifuge (shared)", "ESR stand",
        ),
        ethicsWatch = listOf(
            "finger-prick sampling needs IEC plus trained personnel",
            "biohazard disposal protocol",
            "referral pathway for abnormal values",
        ),
        topics = listOf(
            "Cell injury hypoxic chemical immunological", "Degenerations amyloidosis fatty change",
            "Cell death and necrosis types", "Apoptosis", "Gangrene dry wet gas",
            "Pathological calcifications", "Acute inflammation vascular and cellular response",
            "Chemical mediators of inflammation", "Chronic and granulomatous inflammation",
            "Healing and repair primary and secondary", "Fracture healing",
            "Tuberculosis", "Syphilis", "Thrombosis and embolism",
            "Ischaemia and infarction", "Oedema", "Shock",
            "Nutritional disorders and vitamin deficiencies",
            "Hypersensitivity reactions", "Autoimmunity", "AIDS and hepatitis",
            "Hypertension", "Diabetes mellitus pathology",
            "Atrophy hypertrophy hyperplasia metaplasia dysplasia",
            "Neoplasia classification benign vs malignant", "Metastasis and carcinogenesis",
            "Oncogenes and anti-oncogenes", "Common tumours papilloma SCC BCC",
            "Anemias iron deficiency megaloblastic sickle cell thalassemia",
            "Leukemias", "Lymph node diseases Hodgkin and Non-Hodgkin",
            "Oral cavity diseases lichen planus stomatitis leukoplakia",
            "Salivary gland diseases", "Bone diseases osteomyelitis osteosarcoma",
            "Fibrous dysplasia", "CVS diseases cardiac failure atherosclerosis",
            "Coagulation cascade and disorders", "Platelet disorders",
        ),
    ),

    Subject(
        id = "microbiology",
        name = "Microbiology",
        year = "second",
        blurb = "Bacteriology, virology, mycology and infection control relevant to dental practice and salivary studies.",
        domains = listOf(
            "General Bacteriology & Sterilization",
            "Immunology & Antigens-Antibodies",
            "Cariogenic Streptococci & Dental Plaque Flora",
            "Anaerobic Bacteria (Periodontal Pathogens)",
            "Mycobacteria, Spirochaetes & Actinomycetes",
            "Virology (Herpes, Hepatitis B, HIV)",
            "Mycology (Candidiasis)",
            "Parasitology", "Infection Control in Dental Practice",
            "Antimicrobial Resistance",
        ),
        defaultQuery = "salivary Streptococcus mutans count caries children microbiology",
        synonyms = listOf("S. mutans", "Lactobacillus", "biofilm", "disinfection", "CFU"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-micro-smutans",
                name = "Caries-associated flora",
                keywords = listOf("Streptococcus mutans", "Lactobacillus", "CFU", "saliva"),
                exposures = listOf("caries status", "sugar frequency", "dentifrice type"),
                outcomes = listOf("CFU/mL counts"),
                methods = listOf("salivary sampling", "agar plating", "colony counting"),
            ),
            ClusterSeed(
                id = "seed-micro-disinfection",
                name = "Disinfection efficacy",
                keywords = listOf("disinfectant", "contact time", "efficacy", "surface"),
                exposures = listOf("agent concentration", "contact time"),
                outcomes = listOf("zone of inhibition", "CFU reduction"),
                methods = listOf("swab sampling pre/post", "agar well diffusion"),
            ),
        ),
        equipment = listOf(
            "inoculating loops", "Bunsen burner", "incubator (departmental)",
            "nutrient / Mitis salivarius agar", "autoclave (shared)", "sterile swab sticks",
        ),
        ethicsWatch = listOf(
            "culture safety and biosafety-level compliance",
            "infectious waste autoclaving before disposal",
            "participant anonymity in culture reports",
        ),
        topics = listOf(
            "Bacterial morphology and physiology", "Sterilisation and disinfection methods",
            "Culture media and techniques", "Specimen collection and processing",
            "Bacterial genetics and drug resistance",
            "Immune system structure", "Complement system", "Antigens and immunoglobulins",
            "Antigen-antibody reactions in dentistry", "Immunodeficiency disorders AIDS",
            "Hypersensitivity types", "Autoimmune disorders oral relevance",
            "Staphylococcus and Streptococcus", "Cariogenic streptococci detailed",
            "Mycobacteria tuberculosis and leprosy", "Clostridium tetanus and gas gangrene",
            "Non-sporing anaerobes dental pathogens", "Spirochaetes T pallidum",
            "Actinomycetes", "Herpes viruses", "Hepatitis B virus",
            "HIV structure and transmission", "Mumps measles rubella",
            "Candidiasis", "Oral lesions of systemic mycoses",
            "Protozoa and helminths", "Immunohaematology",
        ),
    ),

    Subject(
        id = "pharmacology",
        name = "Pharmacology",
        year = "second",
        blurb = "Drug actions, adverse effects and rational prescribing with emphasis on dental analgesics and antibiotics.",
        domains = listOf(
            "General Principles (Pharmacokinetics, Pharmacodynamics)",
            "CNS Drugs (Analgesics, Anesthetics, Anxiolytics)",
            "Autonomic Nervous System Drugs",
            "Antimicrobials & Chemotherapy",
            "Cardiovascular Drugs", "Autacoids & Anti-inflammatory",
            "Endocrine Drugs (Diabetes, Steroids)",
            "Dental Pharmacology (Topical Fluorides, Antiseptics, Obtundents)",
            "Prescribing Patterns & Drug Utilization",
            "Emergency Drugs in Dental Practice",
            "Local Anesthetics (Mechanism, Vasoconstrictors)",
        ),
        defaultQuery = "antibiotic prescribing pattern dentists survey amoxicillin awareness",
        synonyms = listOf(
            "prescribing patterns", "amoxicillin", "NSAID",
            "analgesic", "drug utilization",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-pharm-prescribing",
                name = "Prescribing patterns",
                keywords = listOf("antibiotic", "prescribing", "pattern", "dentists"),
                exposures = listOf("clinical scenario", "clinician seniority"),
                outcomes = listOf("drug choice", "dose", "duration"),
                methods = listOf("prescription audit", "structured questionnaire"),
            ),
            ClusterSeed(
                id = "seed-pharm-analgesics",
                name = "Analgesic use",
                keywords = listOf("NSAID", "ibuprofen", "analgesic", "self-medication"),
                exposures = listOf("pain severity", "advice source"),
                outcomes = listOf("usage frequency", "recalled adverse effects"),
                methods = listOf("interview schedule", "pharmacy counter survey"),
            ),
        ),
        equipment = listOf(
            "structured questionnaire forms", "pharmacy OP records access",
            "prescription audit sheets", "spreadsheet for analysis",
        ),
        ethicsWatch = listOf(
            "prescription data anonymization",
            "no intervention on ongoing therapy",
            "permission from records section",
        ),
        topics = listOf(
            "Pharmacokinetics and pharmacodynamics", "Prescription writing and dosage forms",
            "Receptors and drug interactions", "Adverse drug reactions",
            "General anaesthetics", "Hypnotics and sedatives", "Analgesics opioids and NSAIDs",
            "Psychotropics antidepressants antipsychotics", "Antiepileptics",
            "Muscle relaxants", "Local anesthetics mechanism and vasoconstrictors",
            "Sympathomimetics and antiadrenergics", "Parasympathomimetics and parasympatholytics",
            "Antihypertensives", "Antiarrhythmics", "Antianginals", "Diuretics",
            "Antihistamines", "Prostaglandins and leukotrienes", "Bronchodilators",
            "Anticoagulants and coagulants", "Hematinics",
            "Antimicrobials antibiotics", "Antifungals", "Antivirals",
            "Antitubercular and antileprotic drugs", "Anticancer drugs",
            "Insulin and oral hypoglycemics", "Glucocorticoids", "Thyroid drugs",
            "Calcium balance drugs", "Anabolic steroids",
            "Emergency drugs in dental practice", "Dental office emergencies management",
            "Antiseptics astringents obtundents", "Fluorides topical and systemic",
            "Mouthwashes and dentifrices", "Prescribing patterns dentists",
            "Drug utilization evaluation", "Chelating agents BAL EDTA desferrioxamine",
        ),
    ),

    // ---------------- Third BDS ----------------

    Subject(
        id = "oral-pathology",
        name = "Oral Pathology",
        year = "third",
        blurb = "Oral diseases — potentially malignant disorders, mucosal lesions and tumors — with screening and cytology options.",
        domains = listOf(
            "Developmental Disturbances of Teeth & Jaws",
            "Dental Caries (Etiopathogenesis, Microbiology, Prevention)",
            "Pulp & Periapical Pathology", "Periodontal Disease Pathology",
            "Oral Mucosal Diseases (Lichen Planus, Pemphigus, Lupus)",
            "Oral Potentially Malignant Disorders (Leukoplakia, OSMF)",
            "Oral Cancer (TNM, Biopsy, Cytology)",
            "Odontogenic Tumors (Ameloblastoma, Myxoma)",
            "Salivary Gland Tumors", "Cysts of Jaws",
            "Bone Diseases (Fibrous Dysplasia, Paget's, Osteomyelitis)",
            "Forensic Odontology",
        ),
        defaultQuery = "oral potentially malignant disorder leukoplakia OSMF prevalence screening India",
        synonyms = listOf(
            "leukoplakia", "OSMF", "erythroplakia",
            "toluidine blue", "exfoliative cytology",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-opath-osmf",
                name = "OSMF & areca nut",
                keywords = listOf("oral submucous fibrosis", "areca nut", "gutkha", "prevalence"),
                exposures = listOf("areca/gutkha use", "duration", "frequency"),
                outcomes = listOf("OSMF grade", "mouth opening"),
                methods = listOf("screening camp examination", "interincisal distance measurement"),
            ),
            ClusterSeed(
                id = "seed-opath-screening",
                name = "Chairside screening aids",
                keywords = listOf("toluidine blue", "screening", "detection", "sensitivity"),
                exposures = listOf("stain versus naked-eye exam"),
                outcomes = listOf("detection yield", "false positives"),
                methods = listOf("parallel screening", "photographic documentation"),
            ),
        ),
        equipment = listOf(
            "mouth mirrors", "LED torch", "disposable gloves",
            "toluidine blue kit (if sanctioned)", "intraoral camera or phone adapter",
        ),
        ethicsWatch = listOf(
            "mandatory referral pathway for suspicious lesions",
            "biopsy informed consent",
            "photographic confidentiality",
        ),
        topics = listOf(
            "Developmental disturbances of teeth size number structure",
            "Eruption anomalies", "Cleft lip and palate",
            "Dental caries etiopathogenesis microbiology histopathology immunology prevention",
            "Pulp and periapical pathology", "Osteomyelitis of jaws",
            "Space infections and systemic complications",
            "Gingivitis and gingival enlargements", "Periodontitis immunology",
            "Oral bacterial infections TB syphilis ANUG cancrum oris",
            "Viral infections herpes simplex varicella zoster HIV",
            "Fungal infections candidiasis aphthous ulcers",
            "Fibrous dysplasia cherubism osteogenesis imperfecta Paget disease",
            "Cleidocranial dysplasia rickets achondroplasia",
            "TMJ diseases ankylosis myofascial pain dysfunction",
            "Odontogenic cysts dentigerous radicular keratocyst",
            "Non-odontogenic cysts pseudocysts",
            "Odontogenic tumours ameloblastoma myxoma cementoblastoma",
            "Non-odontogenic benign and malignant tumours",
            "Salivary gland tumours pleomorphic adenoma Warthin mucoepidermoid adenoid cystic acinic cell",
            "Granulomas attrition abrasion erosion bruxism",
            "Radiation injury dry socket",
            "Sialolithiasis sialosis sialadenitis xerostomia ptyalism",
            "Oral manifestations of blood nutritional hormonal metabolic diseases",
            "Lichen planus lupus erythematosus pemphigus pemphigoid",
            "Erythema multiforme psoriasis scleroderma",
            "Trigeminal and glossopharyngeal neuralgias",
            "Facial nerve paralysis causalgia burning mouth syndrome",
            "Oral pigmentation and tooth discolouration",
            "Oral precancer and cancer TNM classification",
            "Biopsy types cytology histochemistry",
            "Forensic odontology sex determination age estimation bite marks dental DNA",
        ),
    ),

    Subject(
        id = "oral-medicine",
        name = "Oral Medicine",
        year = "third",
        blurb = "Diagnosis and non-surgical management of oral conditions, orofacial pain and medically compromised patients.",
        domains = listOf(
            "Clinical Diagnosis & Examination",
            "Orofacial Pain (Trigeminal Neuralgia, Referred Pain)",
            "TMJ Disorders & MPDS", "Oral Ulceration & Vesiculobullous Lesions",
            "Salivary Gland Disorders (Sialometry, Sialadenitis)",
            "Xerostomia & Burning Mouth Syndrome",
            "Oral Manifestations of Systemic Disease",
            "Medically Compromised Patient Management",
            "Behavioral Sciences & Psychology",
            "Forensic Odontology (Dental Records, Bite Marks)",
            "Radiotherapy Complications in Oral Cavity",
        ),
        defaultQuery = "temporomandibular disorder prevalence mouth opening dental patients",
        synonyms = listOf("TMD", "temporomandibular", "burning mouth", "xerostomia", "halitosis"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-omed-tmd",
                name = "TMD signs & symptoms",
                keywords = listOf("temporomandibular", "clicking", "deviation", "mouth opening"),
                exposures = listOf("bruxism traits", "stress scores", "posture/screen habits"),
                outcomes = listOf("maximum mouth opening", "VAS pain", "Helkimo index"),
                methods = listOf("ruler measurement", "DC/TMD questionnaire"),
            ),
            ClusterSeed(
                id = "seed-omed-xerostomia",
                name = "Xerostomia & systemic links",
                keywords = listOf("xerostomia", "dry mouth", "medication", "diabetes"),
                exposures = listOf("medication list", "systemic status"),
                outcomes = listOf("sialometry values", "questionnaire scores"),
                methods = listOf("timed sialometry", "symptom questionnaires"),
            ),
        ),
        equipment = listOf(
            "plastic ruler/caliper for mouth opening", "joint-sound stethoscope (optional)",
            "validated questionnaires (DC/TMD printouts)", "VAS scales",
        ),
        ethicsWatch = listOf(
            "questionnaire informed consent",
            "referral for systemic red flags detected during examination",
        ),
        topics = listOf(
            "Clinical diagnosis types and methods", "General physical examination",
            "Orofacial examination and diagnosis", "Saliva diagnostics",
            "Swelling and lump differential diagnosis", "Oral ulceration diagnosis",
            "Pigmented white and red patches", "Lymph node examination",
            "Biopsy and exfoliative cytology", "Haematological and microbiological tests",
            "Teeth developmental abnormalities", "Destruction and discoloration of teeth",
            "Diseases of bone and osteodystrophies", "Osteopetrosis osteogenesis imperfecta",
            "Paget disease fibrous dysplasia cherubism", "TMJ disorders diagnosis",
            "Cysts and tumours soft tissue and hard tissue",
            "Granulomatous diseases TB sarcoidosis Crohn",
            "Trigeminal neuralgia", "Facial pain organic and referred",
            "Altered sensations cacogeusia halitosis", "Tongue disorders",
            "Oral manifestations of metabolic endocrine nutritional blood disorders",
            "Salivary gland diseases sialometry", "Dermatological diseases with oral manifestations",
            "Immunological diseases AIDS leukemia lymphomas",
            "Focal infection theory", "Precancerous lesions and conditions",
            "Bell palsy Frey syndrome MPDS trismus",
            "Forensic odontology bite marks age determination",
            "Psychology behavior determinants memory learning intelligence",
            "Sociology social class family types",
        ),
    ),

    Subject(
        id = "oral-radiology",
        name = "Oral Radiology",
        year = "third",
        blurb = "Radiographic technique and interpretation using EXISTING images — no new exposures for student projects.",
        domains = listOf(
            "Radiation Physics & Safety",
            "Intraoral Radiography (Periapical, Bite-wing, Occlusal)",
            "Extraoral Radiography (OPG, Cephalogram, TMJ)",
            "CBCT Basics & Interpretation",
            "Radiographic Anatomy & Landmarks",
            "Radiographic Pathology Detection",
            "Radiographic Morphometry & Measurements",
            "Incidental Findings on Panoramic Radiographs",
            "Contrast Radiography & Sialography",
            "Radiotherapy Effects on Oral Structures",
        ),
        defaultQuery = "panoramic radiograph incidental findings prevalence retrospective dental",
        synonyms = listOf("OPG", "panoramic", "periapical", "CBCT", "radiographic assessment"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-orad-opg-findings",
                name = "OPG incidental findings",
                keywords = listOf("panoramic", "incidental", "findings", "prevalence"),
                exposures = listOf("age band", "sex"),
                outcomes = listOf("finding frequencies: calcifications, impacted teeth, bone patterns"),
                methods = listOf("retrospective archive review", "dual-examiner reading"),
            ),
            ClusterSeed(
                id = "seed-orad-morphometry",
                name = "Radiographic morphometry",
                keywords = listOf("radiographic", "measurement", "mandibular", "cortical"),
                exposures = listOf("age", "sex"),
                outcomes = listOf("cortical width", "condylar dimensions"),
                methods = listOf("ImageJ calibration on archived images"),
            ),
        ),
        equipment = listOf(
            "existing OPG/IOPA archives", "viewer/lightbox",
            "ImageJ for linear measurements", "anonymized reporting sheets",
        ),
        ethicsWatch = listOf(
            "NO NEW RADIATION for UG projects — archival/retrospective only",
            "image anonymization before analysis",
            "archive custodian permission",
        ),
        topics = listOf(
            "Radiation physics X-ray production", "Compton and photoelectric effects",
            "Biological effects of radiation", "Radiation safety and protection",
            "Image production principles",
            "Intraoral periapical bisecting and parallel technique", "Bite-wing radiography",
            "Occlusal radiography", "Extraoral skull and jaw projections",
            "Cephalometric radiography", "Orthopantomograph OPG",
            "TMJ radiography", "Zygomatic arches",
            "Sialography", "Tomography and CBCT",
            "Factors kVp mA filters collimation screens grids",
            "Darkroom processing and artefacts",
            "Normal anatomical landmarks on radiographs",
            "Radiographic abnormalities interpretation",
            "Faulty radiographs and artefacts",
            "Radiotherapy of orofacial malignancies and complications",
            "Contrast radiography and radioactive isotopes",
            "Radiographic age estimation in forensic odontology",
            "Post-mortem dental identification methods",
        ),
    ),

    Subject(
        id = "periodontology",
        name = "Periodontology",
        year = "third",
        blurb = "Periodontal health, disease classification and prevention with clinical indices ideal for undergraduate studies.",
        domains = listOf(
            "Periodontal Anatomy (Gingiva, PDL, Cementum, Alveolar Bone)",
            "Plaque Biofilm & Calculus", "Gingival Diseases Classification",
            "Periodontitis Classification & Staging",
            "Host Response & Immunopathology",
            "Risk Factors (Smoking, Diabetes, Stress)",
            "Clinical Indices (GI, PI, CPITN, CPI, CAL)",
            "Non-Surgical Therapy (SRP, Curettage)",
            "Surgical Therapy (Flaps, Osseous, GTR)",
            "Mucogingival & Plastic Surgery",
            "Periodontal-Systemic Links (Cardiovascular, Preterm Birth)",
            "Implants & Peri-implantitis",
            "Supportive Periodontal Therapy",
        ),
        defaultQuery = "gingival index plaque periodontal status prevalence dental students",
        synonyms = listOf("gingival index", "probing depth", "CAL", "CPI", "plaque index"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-perio-indices",
                name = "Index-based status surveys",
                keywords = listOf("gingival index", "plaque index", "CPI", "prevalence"),
                exposures = listOf("oral hygiene habits", "smoking", "education level"),
                outcomes = listOf("GI/PI scores", "CPI codes"),
                methods = listOf("standard index examination", "single calibrated examiner"),
            ),
            ClusterSeed(
                id = "seed-perio-systemic",
                name = "Periodontal–systemic links",
                keywords = listOf("periodontitis", "diabetes", "association", "glycemic"),
                exposures = listOf("glycemic status (self-reported or archival)"),
                outcomes = listOf("probing depth", "clinical attachment loss"),
                methods = listOf("cross-sectional clinical examination", "record linkage"),
            ),
        ),
        equipment = listOf(
            "Williams/CPI periodontal probes", "mouth mirrors",
            "plaque disclosing tablets", "sterile gauze", "recording proformas",
        ),
        ethicsWatch = listOf(
            "minimize probing discomfort",
            "cross-infection control between participants",
            "consent for clinical examination",
        ),
        topics = listOf(
            "Periodontal anatomy gingiva junctional epithelium PDL cementum alveolar bone",
            "Defensive mechanisms in oral cavity", "Age changes geriatric dentistry",
            "Classification of periodontal diseases World Workshop",
            "Plaque-associated gingival diseases", "Hormonally influenced gingival diseases",
            "ANUG", "Desquamative gingival diseases", "Gingival enlargement",
            "Epidemiology indices Silness-Loe Plaque Index Loe-Silness Gingival Index CPITN CPI",
            "Spread of inflammation from gingiva", "Periodontal pocket pathogenesis contents",
            "Dental plaque biofilm", "Calculus formation", "Food impaction",
            "Trauma from occlusion", "Habits bruxism tongue thrusting",
            "Iatrogenic factors", "Restorative and orthodontic interrelationships",
            "Systemic diseases diabetes hormones nutrition AIDS leukemia",
            "Risk factors", "Host response cells cytokines",
            "Periodontitis adult aggressive abscess furcation",
            "Diagnosis probing halitosis advanced aids",
            "Treatment plan phases I to IV",
            "Scaling and root planing", "Curettage", "Flap surgery",
            "Osseous surgery grafts guided tissue regeneration",
            "Mucogingival surgery recession classification frenectomy crown lengthening",
            "Periodontal microsurgery", "Splints", "Hypersensitivity management",
            "Implants peri-implantitis implant failure",
            "Supportive periodontal therapy", "Local drug delivery antibiotics",
            "Medically compromised patients periodontal care",
            "Interdisciplinary care pulpo-periodontal",
            "Systemic effects of periodontal disease cardiovascular low birth weight",
        ),
    ),

    Subject(
        id = "endodontics",
        name = "Endodontics",
        year = "third",
        blurb = "Pulp biology, root canal principles and outcomes — often best studied via clinical records and pain scales.",
        domains = listOf(
            "Pulp Biology & Diagnosis", "Vital Pulp Therapy (Capping, Pulpotomy)",
            "Root Canal Treatment Principles", "Access Cavity Preparation",
            "Working Length Determination", "Cleaning & Shaping Techniques",
            "Root Canal Irrigants & Disinfection", "Obturation Methods",
            "Post-Endodontic Restoration", "Endodontic Surgery (Apicectomy)",
            "Traumatized Teeth Management", "Revascularization & Apexification",
            "Nickel-Titanium Instruments", "Lasers in Endodontics",
            "Post-Operative Pain Assessment",
        ),
        defaultQuery = "root canal treatment post-operative pain visual analogue scale working length",
        synonyms = listOf(
            "RCT", "apex locator", "VAS pain",
            "rotary instrumentation", "post-operative pain",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-endo-pain",
                name = "Post-operative pain",
                keywords = listOf("post-operative pain", "VAS", "root canal", "24 hours"),
                exposures = listOf("technique", "intracanal medicament", "pre-op pulpal status"),
                outcomes = listOf("VAS at 24/48 h", "analgesic intake"),
                methods = listOf("phone follow-up sheet", "clinical records review"),
            ),
            ClusterSeed(
                id = "seed-endo-length",
                name = "Working length accuracy",
                keywords = listOf("apex locator", "working length", "accuracy", "radiograph"),
                exposures = listOf("device generation", "canal type"),
                outcomes = listOf("±0.5 mm agreement rates"),
                methods = listOf("archival comparison: apex locator vs radiograph"),
            ),
        ),
        equipment = listOf(
            "electronic apex locator (clinical)", "VAS numeric rating cards",
            "archived RCT records", "existing periapical radiographs",
        ),
        ethicsWatch = listOf(
            "all care delivered under faculty supervision",
            "record-use permission from the department",
            "patient identity protection",
        ),
        topics = listOf(
            "Pulp biology and diagnosis", "Vital pulp therapy pulp capping pulpotomy",
            "Apexogenesis and apexification", "Root canal treatment principles",
            "Rubber dam isolation", "Access cavity preparation",
            "Pulp cavity anatomy", "Working length determination",
            "Cleaning and shaping step-back crown-down", "Root canal irrigants",
            "Intracanal medicaments", "Root canal disinfection",
            "Broken instruments management", "Curved canals management",
            "Perforation management", "Obturation gutta-percha methods",
            "Root canal sealers", "Smear layer",
            "Post-endodontic restoration post and core",
            "Discoloured teeth and bleaching",
            "Traumatized teeth fracture and luxation management",
            "Endodontic surgery apicectomy retrograde filling",
            "Hemisection and replantation", "Root resorption",
            "Lasers in endodontics",
        ),
    ),

    // ---------------- Final BDS ----------------

    Subject(
        id = "omfs",
        name = "Oral & Maxillofacial Surgery",
        year = "final",
        blurb = "Exodontia, minor oral surgery and hospital-based protocols — commonly studied through outcome records.",
        domains = listOf(
            "Exodontia & Surgical Techniques",
            "Impacted Teeth (Classification, Surgical Removal)",
            "Pre-Prosthetic Surgery", "Maxillary Sinus Diseases",
            "TMJ Disorders (Dislocation, Ankylosis, Internal Derangement)",
            "Odontogenic Infections & Fascial Spaces",
            "Fractures of Jaws & Fixation",
            "Salivary Gland Diseases (Sialolithiasis, Tumors)",
            "Cleft Lip & Palate", "Jaw Deformities",
            "Oral Implantology (Osseointegration, Staged Surgery)",
            "Local Anesthesia (Nerve Blocks)",
            "General Anesthesia & IV Sedation",
            "Medical Emergencies in Dental Practice",
        ),
        defaultQuery = "third molar extraction postoperative swelling trismus pain outcome",
        synonyms = listOf("wisdom tooth", "dry socket", "alveolar osteitis", "trismus", "swelling"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-omfs-third-molar",
                name = "Third molar outcomes",
                keywords = listOf("third molar", "extraction", "swelling", "trismus"),
                exposures = listOf("impaction type", "surgical technique", "age"),
                outcomes = listOf("facial swelling mm", "mouth opening", "VAS", "dry socket rate"),
                methods = listOf("day 2/7 follow-up measurements", "OT/OPD register review"),
            ),
            ClusterSeed(
                id = "seed-omfs-emergencies",
                name = "Medical emergencies readiness",
                keywords = listOf("syncope", "emergency", "drugs", "preparedness"),
                exposures = listOf("clinic type", "staff training"),
                outcomes = listOf("emergency kit completeness score", "drill knowledge score"),
                methods = listOf("checklist audit", "staff questionnaire"),
            ),
        ),
        equipment = listOf(
            "measuring tape/digital caliper for facial swelling",
            "maximum-interincisal ruler (trismus)", "VAS cards", "OT/OPD registers",
        ),
        ethicsWatch = listOf(
            "surgical consent processes respected",
            "register data anonymization",
            "no alteration of clinical care for study purposes",
        ),
        topics = listOf(
            "Exodontia forceps and elevators method", "Complications of extraction",
            "Impacted teeth classification mandibular third molar maxillary canine",
            "Pre-prosthetic surgery alveoloplasty frenectomy tori removal",
            "Ridge augmentation sulcus extension",
            "Maxillary sinus diseases sinusitis Caldwell-Luc oro-antral fistula",
            "TMJ disorders dislocation ankylosis internal derangement",
            "Odontogenic infections fascial spaces Ludwig angina",
            "Osteomyelitis", "Benign cystic lesions of jaws",
            "Tumours of oral cavity ameloblastoma carcinoma TNM",
            "Fractures of mandible condyle middle third alveolar",
            "Zygomatic complex fractures fixation methods",
            "Salivary gland diseases sialography sialolithiasis tumours",
            "Jaw deformities prognathism retrognathism open bite",
            "Trigeminal neuralgia facial paralysis nerve injuries",
            "Cleft lip and palate surgical management",
            "Medical emergencies in dental practice",
            "Emergency drugs and IM IV injections",
            "Oral implantology osseointegration Branemark system",
            "Local anesthesia mandibular and maxillary nerve blocks",
            "General anesthesia and IV sedation",
            "CPR and airway management",
        ),
    ),

    Subject(
        id = "pedodontics",
        name = "Pediatric & Preventive Dentistry",
        year = "final",
        blurb = "Children's oral health, behavior guidance and prevention — strong fit for school-based surveys.",
        domains = listOf(
            "Growth & Development (Craniofacial, Dental Arch)",
            "Development of Occlusion", "Dental Caries in Children (ECC, Rampant)",
            "Pediatric Operative Dentistry (SS Crowns, Strip Crowns)",
            "Pediatric Endodontics (Pulpotomy, Pulpectomy)",
            "Traumatic Injuries in Children",
            "Behavior Management (Frankl, Tell-Show-Do)",
            "Preventive & Interceptive Orthodontics",
            "Oral Habits (Thumb Sucking, Tongue Thrust)",
            "Dental Care of Special Needs Children",
            "Fluoride Programs & Sealants",
            "Diet & Nutrition Counseling",
            "School Dental Health Programs",
        ),
        defaultQuery = "early childhood caries prevalence preschool children dmft risk factors",
        synonyms = listOf("ECC", "dmft", "sealants", "fluoride varnish", "behavior management"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-pedo-ecc",
                name = "ECC epidemiology",
                keywords = listOf("early childhood caries", "prevalence", "risk factors", "preschool"),
                exposures = listOf("feeding history", "snacking frequency", "caregiver education"),
                outcomes = listOf("dmft/deft indices"),
                methods = listOf("school screening", "parent interview form"),
            ),
            ClusterSeed(
                id = "seed-pedo-behavior",
                name = "Behavior guidance",
                keywords = listOf("behavior", "anxiety", "Frankl", "management"),
                exposures = listOf("age group", "first visit vs recall visit"),
                outcomes = listOf("Frankl rating", "treatment completion rates"),
                methods = listOf("chairside observation rating"),
            ),
        ),
        equipment = listOf(
            "dmft/DMFT proformas", "mouth mirrors",
            "screening probes", "LED torches", "portable chairs",
        ),
        ethicsWatch = listOf(
            "parental consent AND child assent required",
            "school authority permission",
            "safeguarding during examination",
        ),
        topics = listOf(
            "Growth and development prenatal postnatal craniofacial",
            "Development of occlusion birth to adolescence",
            "Dental anatomy and histology deciduous vs permanent",
            "Eruption sequence and chronology", "Teething disorders",
            "First permanent molar importance",
            "Dental caries in children aetiology",
            "Rampant caries", "Early childhood caries ECC",
            "Diet and nutrition counselling children",
            "Caries activity tests and prediction",
            "Gingival and periodontal diseases in children",
            "Child psychology dental fear",
            "Behavior management non-pharmacological pharmacological",
            "Frankl rating tell-show-do desensitization",
            "Pediatric operative dentistry modified cavity prep",
            "Stainless steel crowns polycarbonate crowns resin crowns",
            "Pediatric endodontics pulpotomy pulpectomy",
            "Traumatic injuries in children classification management",
            "Preventive and interceptive orthodontics",
            "Space maintainers space regainers",
            "Oral habits digit sucking tongue thrusting mouth breathing",
            "Dental care of special needs children",
            "Congenital abnormalities oral manifestations",
            "Dental emergencies in children",
            "Pit and fissure sealants", "Fluoride applications systemic and topical",
            "Dental health education school programs",
            "DMFT dmft index assessment",
        ),
    ),

    Subject(
        id = "orthodontics",
        name = "Orthodontics",
        year = "final",
        blurb = "Malocclusion assessment and appliance effects using indexes and existing study models.",
        domains = listOf(
            "Growth & Development Theories",
            "Classification of Malocclusion (Angle's, Ackerman-Proffit)",
            "Cephalometric Analysis (Steiner's, Downs', Tweed's, Ricketts')",
            "Diagnosis & Treatment Planning",
            "Biomechanics of Tooth Movement",
            "Preventive & Interceptive Orthodontics",
            "Removable Appliances (Expansion, Hawley)",
            "Fixed Appliances (Edgewise, Begg's, Straight-Wire)",
            "Extra-Oral Appliances (Headgear, Chin Cup)",
            "Myofunctional Appliances (Activator, Twin Block, Frankel)",
            "Orthodontic Management of Cleft Lip & Palate",
            "Retention & Relapse",
            "Oral Hygiene with Appliances",
        ),
        defaultQuery = "malocclusion prevalence DAI IOTN adolescents orthodontic treatment need",
        synonyms = listOf("DAI", "IOTN", "overjet", "crowding", "study models"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-ortho-prevalence",
                name = "Treatment need epidemiology",
                keywords = listOf("malocclusion", "prevalence", "DAI", "IOTN", "adolescents"),
                exposures = listOf("age band", "sex", "urban/rural school"),
                outcomes = listOf("DAI scores", "treatment-need categories"),
                methods = listOf("school screening with index rulers"),
            ),
            ClusterSeed(
                id = "seed-ortho-hygiene",
                name = "Appliance & hygiene effects",
                keywords = listOf("fixed appliance", "plaque", "gingivitis", "oral hygiene"),
                exposures = listOf("appliance presence", "hygiene instruction"),
                outcomes = listOf("PI/GI scores around brackets"),
                methods = listOf("indexed examination", "disclosing agent"),
            ),
        ),
        equipment = listOf(
            "DAI/IOTN rulers and charts", "sliding calipers",
            "existing plaster study models", "ImageJ on standardized photos",
        ),
        ethicsWatch = listOf(
            "cast and photo de-identification",
            "no elective appliance changes for study purposes",
        ),
        topics = listOf(
            "Growth and development theories genetic Sicher Scott Moss Petrovic",
            "Morphologic development craniofacial structures",
            "Functional development dental arches and occlusion",
            "Normal occlusion concept", "Malocclusion dental skeletal functional",
            "Classification Angle Simon Lischer Ackerman-Proffit",
            "Stomatognathic function normal and abnormal",
            "Etiology of malocclusion local and general factors",
            "Cephalometric analysis Steiner Downs Tweed Ricketts E-line",
            "Treatment planning dental and skeletal",
            "Anchorage classification and stability",
            "Biomechanics of tooth movement tissue response",
            "Preventive orthodontics", "Interceptive orthodontics serial extraction",
            "Model analyses Pont Ashley Howe Bolton Carey Moyer",
            "Removable appliances clasps springs expansion",
            "Rapid maxillary expansion",
            "Fixed appliances Edgewise Begg straight-wire",
            "Extra-oral appliances headgear chin cup reverse-pull",
            "Myofunctional appliances activator oral screen Frankel bionator twin blocks",
            "Lip bumper inclined planes",
            "Orthodontic management cleft lip and palate",
            "Surgical orthodontics prognathism retrognathism",
            "Retention and relapse", "Wire bending exercises",
            "Clasp construction C-clasp Jackson crib Adams clasp",
            "Hawley appliance bite planes habit-breaking appliances",
        ),
    ),

    Subject(
        id = "public-health",
        name = "Public Health / Community Dentistry",
        year = "final",
        blurb = "Population oral health, health education and program evaluation — camps, schools and communities.",
        domains = listOf(
            "Epidemiology & Biostatistics",
            "Oral Health Survey Methods (WHO)", "Disease Indices",
            "KAP Studies & Health Education",
            "Community Oral Health Programs",
            "Water Fluoridation & Defluoridation",
            "Tobacco Control & Cessation Programs",
            "School Dental Health Programs",
            "Research Methodology & Protocol Design",
            "Practice Management & Ethics",
            "Tele-dentistry & Digital Health",
            "Preventive Dentistry Levels",
        ),
        defaultQuery = "oral health knowledge attitude practice survey tobacco community students",
        synonyms = listOf("KAP study", "health education", "fluoridation", "tobacco cessation", "camp"),
        clusters = listOf(
            ClusterSeed(
                id = "seed-ph-kap",
                name = "Knowledge–attitude–practice",
                keywords = listOf("knowledge", "attitude", "practice", "oral health", "survey"),
                exposures = listOf("education level", "residence", "income proxy"),
                outcomes = listOf("KAP domain scores"),
                methods = listOf("validated questionnaire", "scoring rubric"),
            ),
            ClusterSeed(
                id = "seed-ph-tobacco",
                name = "Tobacco control",
                keywords = listOf("tobacco", "gutkha", "cessation", "awareness", "youth"),
                exposures = listOf("peer influence", "advertising exposure"),
                outcomes = listOf("use prevalence", "quit intention"),
                methods = listOf("anonymous school survey", "GYTS-adapted tool"),
            ),
        ),
        equipment = listOf(
            "WHO oral health assessment forms (modified)", "KAP questionnaires",
            "camp kits (mirrors, probes, torches)", "tally sheets or tablets",
        ),
        ethicsWatch = listOf(
            "institutional and school permissions",
            "anonymized aggregate reporting only",
            "sensitive-question handling (tobacco)",
        ),
        topics = listOf(
            "Public health definition history scope", "Epidemiology general principles",
            "Environmental health sanitation water purification",
            "Health education principles and methods",
            "Public health administration",
            "Ethics and jurisprudence negligence consent",
            "Forensic identification",
            "Nutrition in oral diseases",
            "Behavioral sciences",
            "Health care delivery systems national programmes WHO",
            "Community vs clinical oral health",
            "Epidemiology of dental caries periodontal disease malocclusion",
            "Dental fluorosis epidemiology", "Oral cancer epidemiology",
            "WHO oral health survey methods", "Disease indices DMFT CPI",
            "Delivery of dental care auxiliaries school dental health",
            "Preventive dentistry levels of prevention",
            "Fluoride programmes water fluoridation",
            "Plaque control programs",
            "Research methodology protocol design",
            "Biostatistics data collection presentation",
            "Central tendency and dispersion",
            "Tests of significance sampling bias",
            "Blind trials calibration",
            "Practice management location equipment records",
            "Dentist Act 1948 amendments",
            "Dental Council of India",
            "Tobacco control and cessation programs",
            "Tele-dentistry and digital health",
            "Community oral health assessment surveys",
            "School dental health programs",
        ),
    ),

    Subject(
        id = "interdisciplinary",
        name = "Interdisciplinary Engineering",
        year = "final",
        blurb = "Dental–engineering blend: 3D printing, CAD/CAM, sensors and imaging analytics using college facilities.",
        domains = listOf(
            "3D Printing", "CAD/CAM", "Sensors & IoT",
            "Imaging Analytics", "Biomaterials Engineering", "Instrumentation",
        ),
        defaultQuery = "3D printed dental model dimensional accuracy CAD CAM engineering",
        synonyms = listOf(
            "additive manufacturing", "stereolithography", "ImageJ analysis",
            "sensor prototype", "dimensional accuracy",
        ),
        clusters = listOf(
            ClusterSeed(
                id = "seed-inter-printing",
                name = "Printed model accuracy",
                keywords = listOf("3D printing", "accuracy", "dimensional", "dental model"),
                exposures = listOf("printer type", "layer height", "resin brand"),
                outcomes = listOf("deviation in mm vs master model"),
                methods = listOf("caliper/ImageJ comparison", "repeated prints"),
            ),
            ClusterSeed(
                id = "seed-inter-sensors",
                name = "Chairside sensing",
                keywords = listOf("sensor", "pH", "prototype", "monitoring"),
                exposures = listOf("beverage challenge", "brushing event"),
                outcomes = listOf("signal curves", "repeatability"),
                methods = listOf("bench-top prototype logging", "calibration curve"),
            ),
        ),
        equipment = listOf(
            "departmental/engineering-dept 3D printer and scanner access",
            "ImageJ/Fiji", "digital caliper for verification",
            "low-cost microcontroller kits (via engineering dept)",
        ),
        ethicsWatch = listOf(
            "device safety review before any patient contact",
            "inter-departmental collaboration approval",
            "no clinical claims from bench work",
        ),
        topics = listOf(
            "3D printing additive manufacturing dental models",
            "CAD-CAM dentistry", "Stereolithography",
            "Dimensional accuracy of printed models",
            "Sensor technology and IoT in dentistry",
            "pH monitoring prototypes",
            "ImageJ and digital image analysis",
            "Biomaterials engineering",
            "Dental implant surface engineering",
            "Tissue engineering and scaffolds",
            "Laser applications in dentistry",
            "Computerized cephalometric analysis",
            "Digital impression scanning",
            "Artificial intelligence in dental diagnosis",
        ),
    ),
)

fun subjectsForYear(yearId: String): List<Subject> =
    SUBJECTS.filter { it.year == yearId }

fun getYear(id: String): Year? =
    YEARS.firstOrNull { it.id == id }

fun getSubject(yearId: String, subjectId: String): Subject? =
    SUBJECTS.firstOrNull { it.year == yearId && it.id == subjectId }
